name: Update Manga Chapters

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run Scraper
        run: node scraper.js

      - name: Commit and Push data.json
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Автоматичне оновлення глав" || true
          git push
